apiVersion: v1
kind: Secret
metadata:
  namespace: three-tier
  name: mongo-sec
type: Opaque
data:
  password: cGFzc3dvcmQxMjM= #Three-Tier-Project
  username: YWRtaW4= #admin
  mongo-uri: bW9uZ29kYitzcnY6Ly9rZW5uZXRob3Nob2d3ZTpCVkl1cFRJcW5DMDJCNURaQGNsdXN0ZXIwLm5sOHZscXIubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw
  secret-key: MjU1NTY2M3RmcmZmZ2xtYm4=
  stripe-secret-key: c2tfdGVzdF81MU94V1BxMDJGTHh4Z1BXM3V6SUp5Q3VxWlJGME1Vek1KdGFlcFZpQ0Ntc0R3RE9UTWE4ckxoSWhvbDY4SjhBMEw2RmJBbnRCUXIxWm9FN21sVlBia09aVTdBMEhzbUhzR3p6
