apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo  # ✅ Added env label
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
      env: demo  # ✅ Added env label to match the Service
  template:
    metadata:
      labels:
        role: frontend
        env: demo  # ✅ Added env label inside template
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: frontend
          image: 970547377227.dkr.ecr.us-east-1.amazonaws.com/frontend:46
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
