apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier
spec:
  selector:
    role: frontend
    env: demo  # ✅ Now matches the Deployment labels
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
